/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gym.management.system;

import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnNewMember = new javax.swing.JButton();
        btnUpdateDeleteMember = new javax.swing.JButton();
        btnListOfMembers = new javax.swing.JButton();
        btnPayment = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setBackground(new java.awt.Color(51, 255, 0));
        jToolBar1.setForeground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);

        btnNewMember.setBackground(new java.awt.Color(255, 255, 255));
        btnNewMember.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNewMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gym Icon Jframe/Icon Gym Jframe/new member.png"))); // NOI18N
        btnNewMember.setText("New Member");
        btnNewMember.setFocusable(false);
        btnNewMember.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewMember.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNewMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewMemberActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNewMember);

        btnUpdateDeleteMember.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdateDeleteMember.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUpdateDeleteMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gym Icon Jframe/Icon Gym Jframe/update & delete member.png"))); // NOI18N
        btnUpdateDeleteMember.setText("Update & Delete Member");
        btnUpdateDeleteMember.setFocusable(false);
        btnUpdateDeleteMember.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdateDeleteMember.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUpdateDeleteMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDeleteMemberActionPerformed(evt);
            }
        });
        jToolBar1.add(btnUpdateDeleteMember);

        btnListOfMembers.setBackground(new java.awt.Color(255, 255, 255));
        btnListOfMembers.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnListOfMembers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gym Icon Jframe/Icon Gym Jframe/list of members.png"))); // NOI18N
        btnListOfMembers.setText("List of Members");
        btnListOfMembers.setFocusable(false);
        btnListOfMembers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnListOfMembers.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnListOfMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListOfMembersActionPerformed(evt);
            }
        });
        jToolBar1.add(btnListOfMembers);

        btnPayment.setBackground(new java.awt.Color(255, 255, 255));
        btnPayment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gym Icon Jframe/Icon Gym Jframe/payment.png"))); // NOI18N
        btnPayment.setText("Payment");
        btnPayment.setFocusable(false);
        btnPayment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPayment.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPayment);

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gym Icon Jframe/Icon Gym Jframe/logout.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setFocusable(false);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLogout);

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gym Icon Jframe/Icon Gym Jframe/exit.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.setFocusable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExit);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gym Icon Jframe/Icon Gym Jframe/login background.PNG"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "<html><b style=\"color:orange;\">Do you rally want to Close Application?</b></html>", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(a);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "<html><b style=\"color:orange;\">Do you rally want to Logout?</b></html>", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnNewMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewMemberActionPerformed
        // TODO add your handling code here:
        new NewMember().setVisible(true);
    }//GEN-LAST:event_btnNewMemberActionPerformed

    private void btnUpdateDeleteMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDeleteMemberActionPerformed
        // TODO add your handling code here:
        new UpdateDelete().setVisible(true);
    }//GEN-LAST:event_btnUpdateDeleteMemberActionPerformed

    private void btnListOfMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListOfMembersActionPerformed
        // TODO add your handling code here:
        new ListOfMembers().setVisible(true);
    }//GEN-LAST:event_btnListOfMembersActionPerformed

    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed
        // TODO add your handling code here:
        new Payment().setVisible(true);
    }//GEN-LAST:event_btnPaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnListOfMembers;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNewMember;
    private javax.swing.JButton btnPayment;
    private javax.swing.JButton btnUpdateDeleteMember;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
