/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gym.management.system;

import java.sql.*;
import Project.ConnectionProvider;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class NewMember extends javax.swing.JFrame {

    /**
     * Creates new form NewMember
     */
    static int ID = 0;

    public NewMember() {
        initComponents();
        comboGender.setEnabled(false);
        comboGymTime.setEnabled(false);
        btnSave.setEnabled(false);
    }

    public void validField() {
String id = txtId.getText();
String name = txtName.getText();
        String mobile = txtMobileNumber.getText();
        String email = txtEmail.getText();
        String fatherName = txtFatherName.getText();
        String motherName = txtMotherName.getText();
        String aadhar = txtAadhar.getText();
        String age = txtAge.getText();
        String amount = txtAmountMonth.getText();
        if (!id.equals("") &&!name.equals("") && !mobile.equals("") && !email.equals("") && !fatherName.equals("") && !motherName.equals("") && !age.equals("") && !aadhar.equals("") && !amount.equals("")) {
            comboGender.setEnabled(true);
            comboGymTime.setEnabled(true);
            btnSave.setEnabled(true);
        } else {
            comboGender.setEnabled(false);
            comboGymTime.setEnabled(false);
            btnSave.setEnabled(false);
        }
    }

    public void clear() {
txtId.setText("");
txtName.setText("");
        txtMobileNumber.setText("");
        txtEmail.setText("");
        comboGender.setEnabled(false);
        txtFatherName.setText("");
        txtMotherName.setText("");
        comboGymTime.setEnabled(false);
        txtAadhar.setText("");
        txtAge.setText("");
        txtAmountMonth.setText("");
        btnSave.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMobileNumber = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        comboGender = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtFatherName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtMotherName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        comboGymTime = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtAadhar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtAmountMonth = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(210, 120));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(900, 550));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnClose.setForeground(new java.awt.Color(0, 0, 255));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gym Icon Jframe/Icon Gym Jframe/close.png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 35, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 52)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gym Icon Jframe/Icon Gym Jframe/new member.png"))); // NOI18N
        jLabel1.setText("New Member");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Member Id");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 98, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 134, -1, -1));

        txtName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 163, 250, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Mobile Number");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 207, -1, -1));

        txtMobileNumber.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtMobileNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMobileNumberKeyReleased(evt);
            }
        });
        jPanel1.add(txtMobileNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 243, 250, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Email");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 292, -1, -1));

        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 321, 250, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Gender");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 365, -1, -1));

        comboGender.setEditable(true);
        comboGender.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        comboGender.setForeground(new java.awt.Color(0, 0, 255));
        comboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Unisex", " " }));
        jPanel1.add(comboGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 394, 250, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Father Name");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 438, -1, -1));

        txtFatherName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtFatherName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFatherNameKeyReleased(evt);
            }
        });
        jPanel1.add(txtFatherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 467, 250, -1));

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnSave.setForeground(new java.awt.Color(0, 0, 255));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gym Icon Jframe/Icon Gym Jframe/save.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 511, -1, -1));

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnReset.setForeground(new java.awt.Color(0, 0, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gym Icon Jframe/Icon Gym Jframe/reset.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 511, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Mother Name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 134, -1, -1));

        txtMotherName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtMotherName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMotherNameKeyReleased(evt);
            }
        });
        jPanel1.add(txtMotherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 163, 270, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("Gym Time");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 207, -1, -1));

        comboGymTime.setEditable(true);
        comboGymTime.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        comboGymTime.setForeground(new java.awt.Color(0, 0, 255));
        comboGymTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5:00 AM - 8:00 AM", "6:00 PM - 8:00 PM", " " }));
        jPanel1.add(comboGymTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 243, 270, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("Aadhar Number (Unique ID)");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 292, -1, -1));

        txtAadhar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtAadhar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAadharKeyReleased(evt);
            }
        });
        jPanel1.add(txtAadhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 321, 270, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 255));
        jLabel12.setText("Age");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 365, -1, -1));

        txtAge.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAgeKeyReleased(evt);
            }
        });
        jPanel1.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 394, 270, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 255));
        jLabel13.setText("Amount to pay/month");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 438, -1, -1));

        txtAmountMonth.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtAmountMonth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAmountMonthKeyReleased(evt);
            }
        });
        jPanel1.add(txtAmountMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 467, 270, -1));

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
        validField();
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtMobileNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobileNumberKeyReleased
        // TODO add your handling code here:
        validField();
    }//GEN-LAST:event_txtMobileNumberKeyReleased

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here:
        validField();
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtFatherNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFatherNameKeyReleased
        // TODO add your handling code here:
        validField();
    }//GEN-LAST:event_txtFatherNameKeyReleased

    private void txtMotherNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMotherNameKeyReleased
        // TODO add your handling code here:
        validField();
    }//GEN-LAST:event_txtMotherNameKeyReleased

    private void txtAadharKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAadharKeyReleased
        // TODO add your handling code here:
        validField();
    }//GEN-LAST:event_txtAadharKeyReleased

    private void txtAgeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyReleased
        // TODO add your handling code here:
        validField();
    }//GEN-LAST:event_txtAgeKeyReleased

    private void txtAmountMonthKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountMonthKeyReleased
        // TODO add your handling code here:
        validField();
    }//GEN-LAST:event_txtAmountMonthKeyReleased

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtId.getText());
        String name = txtName.getText();
        String mobile = txtMobileNumber.getText();
        String email = txtEmail.getText();
        String fatherName = txtFatherName.getText();
        String motherName = txtMotherName.getText();
        String aadhar = txtAadhar.getText();
        int age = Integer.parseInt(txtAge.getText());
        String amount = txtAmountMonth.getText();
        String gender = (String) comboGender.getSelectedItem();
        String gymTime = (String) comboGymTime.getSelectedItem();
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            String query = "insert into members values (" + id + ", ' " + name + " ',' " + mobile + " ',' " + email + " ',' " + gender + " ',' " + fatherName + "',' " + motherName + "',' " + gymTime + "'," + age + ",'" + aadhar + "',' " + amount + " ')";
            st.execute(query);
            JOptionPane.showMessageDialog(null, "<html><b style=\"color:green;\">Successfully Updated!</b></html>");
            clear();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboGender;
    private javax.swing.JComboBox<String> comboGymTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAadhar;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAmountMonth;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFatherName;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMobileNumber;
    private javax.swing.JTextField txtMotherName;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
