/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gym.management.system;

import Project.ConnectionProvider;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class UpdateDelete extends javax.swing.JFrame {

    /**
     * Creates new form UpdateDelete
     */
    public UpdateDelete() {
        initComponents();
        setVisiblity();
    }

    public void validFields() {
        String name = txtName.getText();
        String mobile = txtMobileNumber.getText();
        String email = txtEmail.getText();
        String gender = txtGender.getText();
        String father = txtFatherName.getText();
        String mother = txtMotherName.getText();
        String gymTime = txtGymTime.getText();
        String age = txtAge.getText();
        String aadhar = txtAadharNumber.getText();
        String amount = txtAmountMonth.getText();
        if (!name.equals("") && !mobile.equals("") && !email.equals("") && !gender.equals("") && !father.equals("") && !mother.equals("") && !gymTime.equals("") && !age.equals("") && !aadhar.equals("") && !amount.equals("")) {
            btnUpdate.setEnabled(true);
        } else {
            btnUpdate.setEnabled(false);
        }
    }

    public void setVisiblity() {
        if (txtId.getText().equals("")) {
            txtName.setEnabled(false);
            txtMobileNumber.setEnabled(false);
            txtEmail.setEnabled(false);
            txtGender.setEnabled(false);
            txtFatherName.setEnabled(false);
            txtMotherName.setEnabled(false);
            txtGymTime.setEnabled(false);
            txtAadharNumber.setEnabled(false);
            txtAge.setEnabled(false);
            txtAmountMonth.setEnabled(false);
            btnUpdate.setEnabled(false);
            btnDelete.setEnabled(false);
            txtId.setEnabled(true);
            btnSearch.setEnabled(true);
        } else {
            txtId.setEnabled(false);
            txtName.setEnabled(true);
            txtMobileNumber.setEnabled(true);
            txtEmail.setEnabled(true);
            txtGender.setEnabled(true);
            txtFatherName.setEnabled(true);
            txtMotherName.setEnabled(true);
            txtGymTime.setEnabled(true);
            txtAadharNumber.setEnabled(true);
            txtAge.setEnabled(true);
            txtAmountMonth.setEnabled(true);
            btnUpdate.setEnabled(true);
            btnDelete.setEnabled(true);
            btnSearch.setEnabled(false);
        }
    }

    public void clear() {
        txtId.setText("");
        txtName.setText("");
        txtMobileNumber.setText("");
        txtEmail.setText("");
        txtFatherName.setText("");
        txtGender.setText("");
        txtMotherName.setText("");
        txtGymTime.setText("");
        txtAadharNumber.setText("");
        txtAge.setText("");
        txtAmountMonth.setText("");
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMobileNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFatherName = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtMotherName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtGymTime = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtAadharNumber = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtAmountMonth = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(240, 120));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gym Icon Jframe/Icon Gym Jframe/close.png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, -1));

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 42)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gym Icon Jframe/Icon Gym Jframe/update & delete member.png"))); // NOI18N
        jLabel1.setText("UPDATE DELETE MEMBER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Member ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 76, -1, -1));

        txtId.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 73, 102, -1));

        btnSearch.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(0, 0, 255));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gym Icon Jframe/Icon Gym Jframe/search.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 117, -1, -1));

        txtName.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 153, 300, -1));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Mobile Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 197, -1, -1));

        txtMobileNumber.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        txtMobileNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMobileNumberKeyReleased(evt);
            }
        });
        getContentPane().add(txtMobileNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 235, 300, -1));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 279, -1, -1));

        txtEmail.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 315, 300, -1));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Gender");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 359, -1, -1));

        txtGender.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        txtGender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGenderKeyReleased(evt);
            }
        });
        getContentPane().add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 395, 300, -1));

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Father Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 439, -1, -1));

        txtFatherName.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        txtFatherName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFatherNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtFatherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 468, 300, -1));

        btnUpdate.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 0, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gym Icon Jframe/Icon Gym Jframe/save.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 512, -1, -1));

        btnDelete.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 0, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gym Icon Jframe/Icon Gym Jframe/delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 512, -1, -1));

        btnReset.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        btnReset.setForeground(new java.awt.Color(0, 0, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gym Icon Jframe/Icon Gym Jframe/reset.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 512, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Mother Name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 117, -1, -1));

        txtMotherName.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        txtMotherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMotherNameActionPerformed(evt);
            }
        });
        txtMotherName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMotherNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtMotherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 153, 300, -1));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Gym Time");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 197, -1, -1));

        txtGymTime.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        txtGymTime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGymTimeKeyReleased(evt);
            }
        });
        getContentPane().add(txtGymTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 235, 300, -1));

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("Aadhar Number (Unique)");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 279, -1, -1));

        txtAadharNumber.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        txtAadharNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAadharNumberKeyReleased(evt);
            }
        });
        getContentPane().add(txtAadharNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 315, 300, -1));

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("Age");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 359, -1, -1));

        txtAge.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAgeKeyReleased(evt);
            }
        });
        getContentPane().add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 395, 300, -1));

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 255));
        jLabel12.setText("Amount to pay/month");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 439, -1, -1));

        txtAmountMonth.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        txtAmountMonth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAmountMonthKeyReleased(evt);
            }
        });
        getContentPane().add(txtAmountMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 468, 300, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        clear();
        setVisiblity();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtId.getText());
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            String query = "select * from members where id= " + id;
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                if (id == rs.getInt(1)) {
                    txtName.setText(rs.getString(2));
                    txtMobileNumber.setText(rs.getString(3));
                    txtEmail.setText(rs.getString(4));
                    txtFatherName.setText(rs.getString(6));
                    txtGender.setText(rs.getString(5));
                    txtMotherName.setText(rs.getString(7));
                    txtGymTime.setText(rs.getString(8));
                    txtAadharNumber.setText(rs.getString(10));
                    txtAge.setText(rs.getString(9));
                    txtAmountMonth.setText(rs.getString(11));
                    setVisiblity();
                } else {
                    JOptionPane.showMessageDialog(null, "<html><b style=\"color:orange;\">Memeber does  not exits</b></html>");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
        validFields();
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtMobileNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobileNumberKeyReleased
        // TODO add your handling code here:
        validFields();
    }//GEN-LAST:event_txtMobileNumberKeyReleased

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here:
        validFields();
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtGenderKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGenderKeyReleased
        // TODO add your handling code here:
        validFields();
    }//GEN-LAST:event_txtGenderKeyReleased

    private void txtFatherNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFatherNameKeyReleased
        // TODO add your handling code here:
        validFields();
    }//GEN-LAST:event_txtFatherNameKeyReleased

    private void txtMotherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMotherNameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtMotherNameActionPerformed

    private void txtMotherNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMotherNameKeyReleased
        // TODO add your handling code here:
        validFields();
    }//GEN-LAST:event_txtMotherNameKeyReleased

    private void txtGymTimeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGymTimeKeyReleased
        // TODO add your handling code here:
        validFields();
    }//GEN-LAST:event_txtGymTimeKeyReleased

    private void txtAadharNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAadharNumberKeyReleased
        // TODO add your handling code here:
        validFields();
    }//GEN-LAST:event_txtAadharNumberKeyReleased

    private void txtAgeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyReleased
        // TODO add your handling code here:
        validFields();
    }//GEN-LAST:event_txtAgeKeyReleased

    private void txtAmountMonthKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountMonthKeyReleased
        // TODO add your handling code here:
        validFields();
    }//GEN-LAST:event_txtAmountMonthKeyReleased

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtId.getText());
        String name = txtName.getText();
        String mobile = txtMobileNumber.getText();
        String email = txtEmail.getText();
        String gender = txtGender.getText();
        String father = txtFatherName.getText();
        String mother = txtMotherName.getText();
        String gymTime = txtGymTime.getText();
        int age = Integer.parseInt(txtAge.getText());
        String aadhar = txtAadharNumber.getText();
        String amount = txtAmountMonth.getText();
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            String query = "Update members set name = ' " + name + " ', mobile_number =  ' " + mobile + "', email='" + email + "', gender = '" + gender + "', father_name='" + father + "', mother_name= '" + mother + "', gym_time = ' " + gymTime + "', age = " + age + ", aadhar_number='" + aadhar + "', amount_month='" + amount + " ' where id = " + id;
            st.execute(query);
            JOptionPane.showMessageDialog(null, "<html><b style=\"color:green; font-weight:bold; font-style:italic;\">Updated Successfully!</b></html>");
            clear();
            setVisiblity();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtId.getText());
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            String query = "delete from members where id = " + id;
            st.execute(query);
            JOptionPane.showMessageDialog(null, "<html><b style=\"color:orange;\">Deleted Successfully!</b></html>");
            clear();
            setVisiblity();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateDelete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAadharNumber;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAmountMonth;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFatherName;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtGymTime;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMobileNumber;
    private javax.swing.JTextField txtMotherName;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
